server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 182.254.227.85
    username: leyou
    password: 123
    virtual-host: /
  redis:
    host: 182.254.227.85
ly:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_164095133 # 模板名称
